export default {
  HAMMER: 'hammer',
  BACKGROUND: 'background',
  AUSTIN: 'austin',
  LOGO: 'logo',
  STAIR: 'stair',
  GLOBE: 'globe',
  PLANT: 'plant',
  BOOK_STAND: 'bookStand',
  TABLE: 'table',
  OK_BUTTON: 'okButton',
  STAIR_ICON_1: 'stairIcon1',
  STAIR_ICON_2: 'stairIcon2',
  STAIR_ICON_3: 'stairIcon3',
  STAIR_ICON_BACKGROUND: 'stairIconBackground',
  ACTIVE_STAIR_ICON_BACKGROUND: 'activeStairIconBackground',
  NEW_STAIR_1: 'newStair1',
  NEW_STAIR_2: 'newStair2',
  NEW_STAIR_3: 'newStair3',
  NEW_STAIR: 'newStair',
  CONTINUE_BUTTON: 'continueButton',
};
